---
title: ''
output: pdf_document
---

```{r}
library(here)
```

### **Appendix A-3.** Weather API Data Attributes Description

| Domain              | Description                                                                                                                                                                                                                                                                                                                                                                                                               |
|-----------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Address             | "is the address, partial address or latitude,longitude location for which to retrieve weather data. You can also use US ZIP Codes."                                                                                                                                                                                                                                                                                       |
| Date time           | "ISO formatted date, time or datetime value indicating the date and time of the weather data in the locale time zone of the requested location"                                                                                                                                                                                                                                                                           |
| Minimum Temperature | minimum temperature at the location.                                                                                                                                                                                                                                                                                                                                                                                      |
| Maximum Temperature | maximum temperature at the location.                                                                                                                                                                                                                                                                                                                                                                                      |
| Temperature         | temperature at the location                                                                                                                                                                                                                                                                                                                                                                                               |
| Dew Point           | dew point temperature                                                                                                                                                                                                                                                                                                                                                                                                     |
| Relative Humidity   | relative humidity in %                                                                                                                                                                                                                                                                                                                                                                                                    |
| Heat Index          | " a value between 0 and 10 indicating the level of ultra violet (UV) exposure for that hour or day. 10 represents high level of exposure, and 0 represents no exposure. The UV index is calculated based on amount of short wave solar radiation which in turn is a level the cloudiness, type of cloud, time of day, time of year and location altitude. Daily values represent the maximum value of the hourly values." |
| Wind Speed          | average wind speed over a minute                                                                                                                                                                                                                                                                                                                                                                                          |
| Wind Gust           | instantaneous wind speed at a location – May be empty if it is not significantly higher than the wind speed.                                                                                                                                                                                                                                                                                                              |
| Wind Direction      | direction from which the wind is blowing                                                                                                                                                                                                                                                                                                                                                                                  |
| Wind Chill          |                                                                                                                                                                                                                                                                                                                                                                                                                           |
| Precipitation       | the amount of precipitation that fell or is predicted to fall in the period                                                                                                                                                                                                                                                                                                                                               |
| Precipitation Cover | the proportion of hours where there was non-zero precipitation                                                                                                                                                                                                                                                                                                                                                            |
| Snow Depth          | the depth of snow on the ground                                                                                                                                                                                                                                                                                                                                                                                           |
| Visibility          | distance at which distant objects are visible                                                                                                                                                                                                                                                                                                                                                                             |
| Cloud Cover         | how much of the sky is covered in cloud ranging from 0-100%                                                                                                                                                                                                                                                                                                                                                               |
| Sea Level Pressure  | the sea level atmospheric or barometric pressure in millibars (or hectopascals)                                                                                                                                                                                                                                                                                                                                           |
| Weather Type        |                                                                                                                                                                                                                                                                                                                                                                                                                           |
| Latitude            | "is the address, partial address or latitude,longitude location for which to retrieve weather data. You can also use US ZIP Codes."                                                                                                                                                                                                                                                                                       |
| Longitude           | "is the address, partial address or latitude,longitude location for which to retrieve weather data. You can also use US ZIP Codes."                                                                                                                                                                                                                                                                                       |
| Resolved Address    | "is the address, partial address or latitude,longitude location for which to retrieve weather data. You can also use US ZIP Codes."                                                                                                                                                                                                                                                                                       |
| Name                | "is the address, partial address or latitude,longitude location for which to retrieve weather data. You can also use US ZIP Codes."                                                                                                                                                                                                                                                                                       |
| Info                | NA                                                                                                                                                                                                                                                                                                                                                                                                                        |
| Conditions          | textual representation of the weather conditions.                                                                                                                                                                                                                                                                                                                                                                         |

\newpage

### **Appendix A-4.** Dealing with missing values techniques

| Accident attributes                            |                                                                                                                           |
|------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------|
| X                                              | The ID for the record                                                                                                     |
| ACCIDENT_NO                                    | The accident id that the person was associated with                                                                       |
| FATAL_ACCIDENT                                 | Categorical variable on whether the person was involved in an accident with fatalities. This will be our target variable. |
| ACCIDENTDATE                                   | The date of the accident                                                                                                  |
| ACCIDENTTIME                                   | The time of the accident                                                                                                  |
| DAY_OF_WEEK                                    | The day of week in numerical form                                                                                         |
| Day_Week_Description                           | The day of week in categorical form                                                                                       |
| NO_OF_VEHICLES                                 | The number of vehicles involved in the accident                                                                           |
| NO_PERSONS                                     | The number of people involved in the accident                                                                             |
| NO_PERSONS_INJ_2                               | The number of people with an injury level of 2                                                                            |
| NO_PERSONS_INJ_3                               | The number of people with an injury level of 3                                                                            |
| NO_PERSONS_KILLED                              | The number of people died                                                                                                 |
| NO_PERSONS_NOT_INJ                             | The number of people not injured                                                                                          |
| Accident_Type_Desc                             | Description of the accident type                                                                                          |
| DCA_Description                                | " ‘Definition for Coding Accidents’ code description. Basically, the category of the accident. "                          |
| SEVERITY                                       | The severity of the accident in numerical form                                                                            |
|                                                |                                                                                                                           |
| Accident location and environmental attributes |                                                                                                                           |
| SPEED_ZONE                                     | The speed zone of where the accident occurred                                                                             |
| Road_Geometry_Desc                             | The road geometry description                                                                                             |
| ROAD_NAME                                      | Name of the road the accident occurred on                                                                                 |
| ROAD_TYPE                                      | Type of the road the accident occurred on                                                                                 |
| ROAD_NAME_INT                                  | Name of the road intersection the accident is closest to                                                                  |
| ROAD_TYPE_INT                                  | Type of the road intersection the accident is closest to                                                                  |
| LGA_NAME                                       | The local government area name                                                                                            |
| Road_Surface_Type_Desc                         | The road surface type description                                                                                         |
| Surface_Cond_Desc                              | The road surface condition                                                                                                |
| LIGHT_CONDITION                                | The light condition in numerical form                                                                                     |
| Light_Condition_Desc                           | The light condition in categorical form                                                                                   |
|                                                |                                                                                                                           |
| Weather attributes                             |                                                                                                                           |
| Atmosph_Cond_Desc                              | The atmosphere condition description                                                                                      |
| Temperature                                    | The average temperature throughout the day                                                                                |
| DewPoint                                       | The average dewpoint throughout the day                                                                                   |
| RelativeHumidity                               | The average relative humidity throughout the day                                                                          |
| WindSpeed                                      | The average windspeed throughout the day                                                                                  |
| Precipitation                                  | The total precipitation throughout the day                                                                                |
| Visibility                                     | The average visibility throughout the day. The distance that can seen in daylight.                                        |
| CloudCover                                     | The average cloud cover throughout the day                                                                                |
| WeatherType                                    | The weather types throughout the day                                                                                      |


\newpage

### **Appendix A-5.** Dealing with missing values techniques

| Techniques                                    | Definition                                                                                                                                                                                                                                                                                                                                                                   |
|----------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Drop / Remove all missing values              | The easiest method of dealing with missing values. This generally will exclude all those missing values out of the dataset by removing/deleting column rows.                                                                                                                                                                                                                 |
| Imputation Using Mode Values                  | "Mode/Most frequent is another statistical strategy to impute missing values. It works with categorical features (strings or numerical representations) by replacing missing data with the most frequent values within each column (Badr, 2019)."                                                                                                                            |
| Imputation Using (Mean/Median) Values         | "A widely common and accepted approach to missing data is to replace the NA with the mean. The nature of this method does not distort or change the distribution of values within each feature. Furthermore, the simplicity to implement this was the driving factor in this method being chosen (Badr, 2019)."                                                              |
| Amelia predictive model (Multiple Imputation) | "Multiple imputation involves imputing values for each missing cell in your data matrix and creating “completed” data sets. Across these completed data sets, the observed values are the same, but the missing values are filled in with a distribution of imputations that reflect the uncertainty about the missing data. (Amelia II: A Program for Missing Data, n.d.)." |
| K-nearest neighbor                            | The k nearest neighbors is an algorithm that is used for simple classification. The algorithm uses ‘feature similarity’ to predict the values of any new data points.                                                                                                                                                                                                        |
|                                               | "This is useful in making predictions about the missing values by finding the k’s closest neighbors to the observation with missing data and then imputing them based on the non-missing values in the neighborhood (Badr, 2019)."                                                                                                                                           |
| Random Imputation                             | "On the other hand, replace missing numerical data with mean and replace missing categorical data at existing distribution are the two techniques we chose to deal with missing values in our dataset."                                                                                                                                                                      |

\newpage

### **Appendix A-6.** Assign Dummy Variables Techniques

| Techniques                                                                                                                                                                                                                                    | Definition                                                                                                                                                      |                                                                                                                                                                            |                                              |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------|
| Label encoding                                                                                                                                                                                                                                | "A popular encoding technique for categorical information that is used in many applications. In this technique                                                  | a unique integer is assigned to each label depending on the alphabetical order of the labels.                                                                              |                                              |
| However                                                                                                                                                                                                                                       | depending upon the data values and type of data                                                                                                                 | label encoding induces a new problem since it uses number sequencing. The problem using the number is that they introduce relation/comparison between them when in reality | there is no relation between these values. " |
| One Hot Encoding                                                                                                                                                                                                                              | "This technique can solve this problem by converting each category value into a new column and assigned a 1 or 0 (notation for true/false) value to the column. |                                                                                                                                                                            |                                              |
| Though this approach eliminates the hierarchy/order issues but does have the downside of adding more columns to the data set. It can cause the number of columns to expand greatly if you have many unique values in a category column (Yadav | 2019)."                                                                                                                                                         |                                                                                                                                                                            |                                              |
|                                                                                                                                                                                                                                               |                                                                                                                                                                 |                                                                                                                                                                            |                                              |

\newpage