---
title: " "
output: pdf_document
header-includes:
  - \usepackage{float}
  - \usepackage{sectsty}
---

# Introduction

Death from road traffic crashes continue to be major global public health problems across Australia \citep*{RN2}. A road traffic fatality results from a complex interaction of **human**, **technical** and **environmental** factors, and different causes behind road vehicle crashes require different measures to reduce their impacts.  

# Methodology 

CRISP-DM methodology will be used for this project which is used in most of the data science projects in the industry \citep*{wijaya-2021}. The six steps are as follows: 

* Business Understanding 

* Data Understanding 

* Data Preparation 

* Modeling 

* Evaluation 

* Deployment (Not in the scope of this assignment)


# Business Understanding 

Our group study assesses how strongly the variation between some environmental factors and the increased risk of vehicle crash-related mortality in Victoria, Australia. The findings are relevant in the context of impact-based warnings for both road users, road maintenance and traffic management authorities, as well as rescue forces.  

On the one hand, this is relevant for raising the effectiveness of road weather warning services, while on the other hand, it may help rescue and medical services to project the number of emergencies in designated regions in case weather forecasts foresee bad conditions for road transport. 