---
title: ''
output: pdf_document
---

# Conclusions and Limitations 

The project is based on the rationale to reduce the number of deaths caused by motor vehicle accidents on Australian roads. The data has been collected from the Victoria government accidents data using an API. The data will be cleaned, explored and visualized using various R libraries and will be prepared for modelling. The major models used will be a linear regression models aiming to classify the accidents causing or not causing deaths and then finding the major factors leading to a death. The model will be evaluated using various techniques. The model efficiency goal is set to be above 80% accurate.  

The major limitation of the project is that we do not have data where the accidents are not happening, so we had to choose the target variable as the fatality in an accident. This can cause a bias as we might have no accidents with the same conditions and factors. We had to assume that the probability of occurrence of an accident in the same conditions is 1. 